name: test-workflow

on:
  workflow_dispatch:

jobs:
  printhellow:
    runs-on: ubuntu-latest

    steps:
      - name: printing
        shell: bash
        run: | 
          echo " Application Testing"
